### ISSUE TITLE
having 'verbose: true' in workflow file means _check_for_inline_script will not display findings for inline scripts found

### ISSUE THREAD

**Issue by 6mile** [bin3xish477/asa#1]
For some reason when you have the ``` verbose: true ``` parameter set in the ASA workflow file you will not see any findings for inline scripts found.

The way to test this yourself is create a GitHub Action Workflow file with a ``` run: ``` action and if you set the ``` verbose: true ``` parameter you will not see the notification for that finding.  If you then remove the ``` verbose: true ``` from the workflow file you will then be able to see the workflow finding.

Please see analyzer/analyzer.py

```
    def _check_for_inline_script(self) -> bool:
        passed = True
        for job in self.jobs.keys():
            steps = self.jobs[job]["steps"]
            for step in steps:
                if "run" in step:
                    if self.verbose:
                        print(
                            f"{Colors.LIGHT_GRAY}INFO{Colors.END} found inline script in job('{job}').step('{step['name']}')"
                        )
                    passed = False
        return passed
```

**Comment by bin3xish477** [comment]
Hello @6mile , can you provide the workflow example you are using

**Comment by bin3xish477** [comment]
When I run it with `verbose: true`, I do see the output for the `check_for_inline_script` check:

<img width="927" alt="image" src="https://github.com/bin3xish477/asa/assets/44281620/05e69a2d-9754-47db-92e8-9fc9027b8a46">


Here is the workflow I am using (**NOTE**: I've set the `ignore-checks` argument to an empty string). 

```yaml
name: 'RunActionsSecurityAnalzyer'
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**'
jobs:
  RunAsa:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3
    - name: "Run asa scanner"
      uses: "bin3xish477/asa@a6f5eb8c20e936c07326a1eb6aa6427b25494045"
      with:
        dir: "./actions/"
        verbose: true
        no-summary: true
        ignore-checks: ''
      continue-on-error: true # adding this since this workflow is always expected to fail

```

**Comment by 6mile** [comment]
Heya mate,
I have used multiple workflow file versions as I have tested the necessity and functionality of each parameter.   So for example here's my current version:

``` 
name: 'Pauls version of Check All GitHub Actions for Security Issues via bin3xish477 ASA'
on:
  push:
jobs:
  RunAsa:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3
    - name: "Run asa scanner"
      uses: "bin3xish477/asa@a6f5eb8c20e936c07326a1eb6aa6427b25494045"
      with:
        verbose: true
      continue-on-error: true
```
![image](https://github.com/bin3xish477/asa/assets/7798480/ffe48133-28bc-42b9-8f36-a126655da046)

Then, if i remove the ``` verbose: true ``` line I get this:

![image](https://github.com/bin3xish477/asa/assets/7798480/99cd9399-a09c-48f1-9824-9939a38cbe4b)

**Comment by bin3xish477** [comment]
Oh I see, there appears to be an error during the execution of the `_check_for_inline_script` method that occurs when a step doesn't have a `name`. It appears that name field isn't required, according to the GitHub [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name).

I'll put a check here for the existence of `name` key. Hopefully this fixes the issue!

**Comment by bin3xish477** [comment]
@6mile try using the following workflow and see if it fixes the issue:

```yaml
name: 'Pauls version of Check All GitHub Actions for Security Issues via bin3xish477 ASA'
on:
  push:
    paths:
      - '.github/workflows/**'
jobs:
  RunAsa:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3
    - name: "Run asa scanner"
      uses: "bin3xish477/asa@ee733379e314d44f1a960a70339ee5e5d19e404d"
      with:
        verbose: true
      continue-on-error: true

```
